[theme]
# Color principal para botones activos, barras de progreso y acentos
primaryColor = "#ADAF7E"

# Color de fondo principal de la aplicación
backgroundColor = "#EDEDE9"

# Color de fondo de la barra lateral (sidebar) y widgets secundarios
secondaryBackgroundColor = "#D4D7AD"

# Color del texto (puedes ajustarlo según prefieras, aquí uno oscuro para contraste)
textColor = "#31333F"

[client]
# Oculta el botón de "Deploy" arriba a la derecha
toolbarMode = "minimal"

[ui]
# En versiones recientes de Streamlit, esto ayuda a simplificar la UI
hideTopBar = true
